### ISSUE TITLE
PStore trouble when loading mnist

### ISSUE THREAD

**Issue by kojix2** [red-data-tools/red-chainer#10]
Hello
Thank you for your interesting project. 

I tried mnist example and the following error occurred.

```console
/path/.rbenv/versions/2.4.2/lib/ruby/2.4.0/pstore.rb:482:in `load': incompatible marshal file format (can't be read) (TypeError)
	format version 4.8 required; 80.75 given
	from /path/.rbenv/versions/2.4.2/lib/ruby/2.4.0/pstore.rb:482:in `load'
	from /path/.rbenv/versions/2.4.2/lib/ruby/2.4.0/pstore.rb:417:in `load_data'
	from /path/.rbenv/versions/2.4.2/lib/ruby/2.4.0/pstore.rb:328:in `transaction'
	from /path/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/red-chainer-0.1.0/lib/chainer/dataset/download.rb:38:in `cache_or_load_file'
	from /path/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/red-chainer-0.1.0/lib/chainer/datasets/mnist.rb:52:in `retrieve_mnist'
	from /path/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/red-chainer-0.1.0/lib/chainer/datasets/mnist.rb:39:in `retrieve_mnist_training'
	from /path/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/red-chainer-0.1.0/lib/chainer/datasets/mnist.rb:7:in `get_mnist'
	from examples/mnist.rb:29:in `<main>'
```

This problem was similar to the following issue.
https://github.com/nanoc/nanoc/pull/418#diff-4d61f501cb8be493c5421a39289eda1e
https://github.com/nanoc/nanoc/pull/418/files#diff-4d61f501cb8be493c5421a39289eda1eR74

The following changes solved the problem.
https://github.com/kojix2/red-chainer/commit/f62489f3aec1a8e73708dc0f5f730eebd8a80296
I am not a programmer, so please fix it in a better way.

Thank you

**Comment by hatappi** [comment]
@kojix2 
Thank you for creating an issue.
Could you tell us the execution environment?

**Comment by kojix2** [comment]
Ubuntu x86_64
ruby 2.4.2

**Comment by hatappi** [comment]
@kojix2 
I fixed this issue and merge to master branch by [PR](https://github.com/red-data-tools/red-chainer/pull/12).
Please check in your environment.

**Comment by kojix2** [comment]
This works correctly in my computer.
Thank you.

```console
iteration 9996
> [0.99]
iteration 9997
> [1.0]
iteration 9998
> [1.0]
iteration 9999
> [0.98]
iteration 10000
> [1.0]

```
