### ISSUE TITLE
When GPU support is turned on, VGG 16 will be slow.

### ISSUE THREAD

**Issue by kojix2** [red-data-tools/red-chainer#79]
I do not know why, but the sample Vgg 16 gets slower with Cumo. 
Numo is faster in my environment.

**Comment by sonots** [comment]
I mean that convolutional networks are slow yet.

**Comment by kojix2** [comment]
Thank you.
But I remember that the original Python chainer got faster without using cuDNN.
So I think there are other problems besides cuDNN. 
(Perhaps it may be a problem of my local environment on my computer)

**Comment by sonots-zozo** [comment]
thanks, I might be able to investigate if you push the vgg example.
(But, I feel I should spend my time to support cuDNN now)

**Comment by kojix2** [comment]
Currently, convolution_2d does not seem to support Cumo. 
I may have misunderstood something.

I close this issue.
